# Vsense Smart Home Website Configuration

# Theme Settings
minimal_mistakes_skin    : "mint"  # Choose a clean, modern look

# Site Settings
locale                   : "en-US"
title                    : "Vsense Smart Home"
title_separator          : "-"
subtitle                 : "Smarter Living Starts Here"
name                     : "Vsense"
description              : "Explore cutting-edge smart home solutions from Vsense. From lighting automation to energy efficiency, we make your home smarter."
url                      : "https://vsense.tech" # Replace with your actual domain
baseurl                  : "" # No subpath
repository               : "vsense/vsense-site"
logo                     : "/assets/images/vsense-logo.png"  # Optional: logo file path
masthead_title           : " "  # Show logo only
breadcrumbs              : true
words_per_minute         : 180
enable_copy_code_button  : false
copyright                : "Vsense"
copyright_url            : "https://vsense.tech"

# Comments - Disabled for static site
comments:
  provider: false

# Search (recommended for content-heavy sites)
search                   : true
search_full_content      : true
search_provider          : lunr

# SEO Verification (optional, helpful for Google indexing)
google_site_verification : YOUR_GOOGLE_VERIFICATION_CODE

# Social Sharing Image
og_image: "/assets/images/og-image.jpg"  # Update with a clean shareable image

# Social Media Links
social:
  type : Organization
  name : Vsense
  links:
    - "https://www.facebook.com/vsensehome"
    - "https://www.instagram.com/vsensehome"
    - "https://www.linkedin.com/company/vsensehome"

# Analytics (Google GA4)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XXXXXXXXXX"  # Replace with your GA ID

# Site Author
author:
  name    : "Vsense Team"
  avatar  : "/assets/images/team.jpg"
  bio     : "The innovators behind Vsense – building the future of smart living."
  location: "New Zealand"
  email   : "hello@vsense.tech"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hello@vsense.tech"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/vsensehome"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/vsensehome"

# Footer
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/vsensehome"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/vsensehome"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/vsensehome"

# Reading Files and Excludes
include:
  - .htaccess
  - _pages
exclude:
  - node_modules
  - vendor
  - README
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - .gitignore

# Markdown and Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false

# Sass Settings
sass:
  sass_dir: _sass
  style: compressed

# Permalink & Timezone
permalink: /:categories/:title/
timezone: Pacific/Auckland

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      related: true
